apiVersion: v1
kind: Service
metadata:
  name: monolith-service
spec:
  type: NodePort
  selector:
    app: monolith
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
